Main
jup-ag/token-list pull request #1065
Opened 2024-01-13 08:49 UTC by MONKEycHIMP

# Validate [HONK](https://solscan.io/token/3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Honk_Solana/status/1746091270509105165?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

2024-01-19 03:57 UTC, MONKEycHIMP commented on validated-tokens.csv
> +Honk,HONK,3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB,9,https://bafkreia5nmyxbrxshpiebsakviidhkfuoevpcyzonwov7bmaovce5ekzym.ipfs.nftstorage.link,true
HONK is listed on CG & trading on Jupiter under ALL : 
CG : https://www.coingecko.com/en/coins/honk
JUPITER :  https://jup.ag/swap/SOL-HONK_3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB

2024-01-19 04:04 UTC, MONKEycHIMP reviewed
Validate Honk

2024-01-19 04:05 UTC, MONKEycHIMP reviewed
Validate HONK

2024-01-20 02:56 UTC, MONKEycHIMP commented
https://twitter.com/Honk_Solana/status/1747831167859278157?t=pt1VHN5LGvImik28VqY2rg&s=19

2024-01-22 03:27 UTC, 0xSoju2 requested changes
Declined because this PR screws over other tokens + adds 2 tokens.

2024-01-22 13:43 UTC, closed without merging