Validate BOOP
jup-ag/token-list pull request #126
Opened 2023-03-31 11:19 UTC by HasukiOfficial

# Validate [BOOP](https://solscan.io/token/CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- https://twitter.com/HasukiNFTs/status/1641761410299355137
- Coingecko/ CMC URL (If available): Not available.

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-03-31 12:03 UTC, scastradio commented
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8
 Symbol: BOOP
 Token Decimals: 10
 Token icon: https://arweave.net/YTXQL4GzZTCijix2GEVv_nwNs4hlgAaqcimTT6e-H5Q
 On-chain metadata matches
 No duplication on Jupiter's strict list

2023-04-02 19:31 UTC, Timoon21 requested changes
LogoURI don't match on-chain metadata.

2023-04-02 19:31 UTC, Timoon21 commented on validated-tokens.csv
> +BOOP,BOOP,CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8,10,https://arweave.net/YTXQL4GzZTCijix2GEVv_nwNs4hlgAaqcimTT6e-H5Q,true
```suggestion
BOOP,BOOP,CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8,10,https://arweave.net/2ArDrNlyF34gjZ7UdXmMVl_ET9igdcyDiAY-VFsw3ao,true
```

2023-04-02 19:38 UTC, Timoon21 commented
> I can hereby attest that the provided information are accurate, and the token is valid.
> 
> Mint address: CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8 Symbol: BOOP Token Decimals: 10 Token icon: https://arweave.net/YTXQL4GzZTCijix2GEVv_nwNs4hlgAaqcimTT6e-H5Q On-chain metadata matches No duplication on Jupiter's strict list

Please review carefully. This is not the token icon file.

2023-04-02 19:38 UTC, Timoon21 commented
> I can hereby attest that the provided information are accurate, and the token is valid.
> 
> Mint address: CCRJohp9bfQdhZCvCe7MzUQuXMJkKBi4XCjUq3A2YqN8 Symbol: BOOP Token Decimals: 10 Token icon: https://arweave.net/YTXQL4GzZTCijix2GEVv_nwNs4hlgAaqcimTT6e-H5Q On-chain metadata matches No duplication on Jupiter's strict list

Please review carefully. This is not the token icon file.

2023-04-02 19:46 UTC, HasukiOfficial commented
Token icon file updated

2023-04-05 20:12 UTC, Timoon21 approved these changes
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

2023-04-05 23:37 UTC, LJQZZZ123 commented
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] The same token symbol can be searched on CMC but seems unrelated
- [ ] No duplication on Jupiter's strict list
- [ ] Known by the community

> https://coinmarketcap.com/currencies/boop/

2023-04-05 23:37 UTC, LJQZZZ123 approved these changes

2023-04-06 10:46 UTC, merged