Validate FLTH
jup-ag/token-list pull request #149
Opened 2023-04-24 15:31 UTC by anselsol

# Validate [FLTH](https://solscan.io/token/FLTHudk5B5zag7JmGXqrYrFfey6otevLQA6jm1UHHLEE)

## Attestations
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [tweet]()
- Coingecko URL: https://www.coingecko.com/en/coins/liberty-square-filth

## Validation
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

🤝

2023-04-28 04:48 UTC, meijiao approved these changes

2023-04-29 15:08 UTC, Timoon21 requested changes
- [ ] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

2023-04-29 15:08 UTC, Timoon21 commented on validated-tokens.csv
> +FLTH Token,FLTH,FLTHudk5B5zag7JmGXqrYrFfey6otevLQA6jm1UHHLEE,9,https://www.arweave.net/6cZ-d9BnAsCqxkpzazYmKjLpUN2kE-jYnU3WDV4_lo0?ext=png,true
```suggestion
FLTH,FLTH,FLTHudk5B5zag7JmGXqrYrFfey6otevLQA6jm1UHHLEE,9,https://www.arweave.net/6cZ-d9BnAsCqxkpzazYmKjLpUN2kE-jYnU3WDV4_lo0?ext=png,true
```

2023-04-29 23:49 UTC, Timoon21 submitted a review, later dismissed

2023-05-01 04:28 UTC, benlvb approved these changes

2023-05-01 10:57 UTC, merged