Add Companion $CMPN to Jupiter Exchange
jup-ag/token-list pull request #160
Opened 2023-05-04 15:53 UTC by flyfishingg

# Validate [{CMPN}](https://solscan.io/token/9tQhCmFtCh56qqf9szLQ8dNjYcd4TTv6MWPpw6MqLubu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Companion_to/status/1654134759789047808
- Coingecko/ CMC URL (If available): [https://coinmarketcap.com/currencies/companion/](https://coinmarketcap.com/currencies/companion/)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-05-04 20:44 UTC, Timoon21 requested changes
Request change to match metadata

2023-05-04 20:44 UTC, Timoon21 commented on validated-tokens.csv
> +Companion,CMPN,9tQhCmFtCh56qqf9szLQ8dNjYcd4TTv6MWPpw6MqLubu,6,https://a6ou2q2zunxut3ietvj34smyyr25ymnx3knyykrb4jncaiobfeda.arweave.net/B51NQ1mjb0ntBJ1TvkmYxHXcMbfam4wqIeJaICHBKQY,true
```suggestion
Companion,CMPN,9tQhCmFtCh56qqf9szLQ8dNjYcd4TTv6MWPpw6MqLubu,6,https://www.arweave.net/B51NQ1mjb0ntBJ1TvkmYxHXcMbfam4wqIeJaICHBKQY?ext=png,true
```

2023-05-05 22:36 UTC, Timoon21 approved these changes

2023-05-05 22:37 UTC, Timoon21 submitted a review, later dismissed
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

2023-05-06 12:56 UTC, meijiao approved these changes

2023-05-06 12:56 UTC, merged