Validate $ANON
jup-ag/token-list pull request #201
Opened 2023-05-16 13:02 UTC by Pandybary

Validate Anon

# Validate [$ANON](https://solscan.io/token/4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/AnonCoinSol/status/1657374688304046082
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-05-16 19:23 UTC, Pandybary commented
I can hereby attest that the provided information are accurate, and the token is valid.
 
Mint address: 
4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R
Name: ANON
Symbol: $ANON
Token Decimals: 7
Token icon: https://arweave.net/kPNmtSROIdowJp2fUp1A02vqEwD-9bduQTbgiZugsd0
On-chain metadata matches
No duplication on Jupiter's strict list

2023-05-16 20:14 UTC, kkrkishore commented
Mint address:
4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R
Name: ANON
Symbol: $ANON
Token Decimals: 7
Token icon: https://arweave.net/hSyqZL4l_8wpk291raYcTZlBs0hNzHncklBQWALOB8E
On-chain metadata matches
No duplication on Jupiter's strict list

2023-05-16 20:42 UTC, Timoon21 requested changes
- [ ] On-chain metadata matches the PR

2023-05-16 20:42 UTC, Timoon21 commented on validated-tokens.csv
> +Anon,$ANON,4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R,7,https://arweave.net/kPNmtSROIdowJp2fUp1A02vqEwD-9bduQTbgiZugsd0,true
```suggestion
ANON,$ANON,4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R,7,https://arweave.net/hSyqZL4l_8wpk291raYcTZlBs0hNzHncklBQWALOB8E,true
```

2023-05-16 20:43 UTC, Timoon21 submitted a review, later dismissed
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

2023-05-17 04:17 UTC, Timoon21 approved these changes

2023-05-17 07:21 UTC, MGAdON commented
All of the data is correct and matches.

Mint address:
4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R
Name: ANON
Symbol: $ANON
Token Decimals: 7
Token icon: https://arweave.net/hSyqZL4l_8wpk291raYcTZlBs0hNzHncklBQWALOB8E
On-chain metadata matches
No duplication on Jupiter's strict list

2023-05-17 07:23 UTC, merged