Validate JIMMY
jup-ag/token-list pull request #205
Opened 2023-05-19 00:42 UTC by smallinvestor

# Validate [{JIMMY}](https://solscan.io/token/94XduSfSnyas7jAEFSJSXiCi1xQ4mENWcii1aCvjVuqu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/jimmycoinsol/status/1659353316864802817
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/3bkCHXmjjTvp23JRgokb1jbvoBTcpyGDKroyKmzbU4eV/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-05-19 11:11 UTC, Pandybary commented
I proved infomations and i can say that everything is correct.

Mint address: 94XduSfSnyas7jAEFSJSXiCi1xQ4mENWcii1aCvjVuqu
Name: JIMMY
Symbol: JIMMY
Token Decimals: 9
Token icon: https://www.jimmycoinsol.vip/static/media/logo.a7fcc2c98544dcad25a5.png
On-chain metadata matches
No duplication on Jupiter's strict list

2023-05-21 20:42 UTC, Timoon21 requested changes
- [x] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation


Please update the PR to match on-chain metadata

2023-05-21 20:42 UTC, Timoon21 commented on validated-tokens.csv
> +JIMMY,JIMMY,94XduSfSnyas7jAEFSJSXiCi1xQ4mENWcii1aCvjVuqu,9,https://www.jimmycoinsol.vip/static/media/logo.a7fcc2c98544dcad25a5.png,true
```suggestion
JIMMY,JIMMY,94XduSfSnyas7jAEFSJSXiCi1xQ4mENWcii1aCvjVuqu,9,https://arweave.net/5NmSALkMrjr5p33OrjuQlA5a3LRPLv0Ta07SnEWt1fk,true
```

2023-05-22 12:24 UTC, meijiao requested changes
pls match onchain meta

2023-05-23 04:34 UTC, meijiao commented
Closing this PR -- Please read the review and open a new PR when you are ready.

2023-05-23 04:34 UTC, closed without merging