Validate $YOLO
jup-ag/token-list pull request #235
Opened 2023-06-08 13:11 UTC by nolomax

# Validate $[YOLO](https://solscan.io/token/4jE4VuqFWZfmSXjTDD5KUoN2qkVu96nPTPj4mhs5PA1W)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/YoloNoloBot/status/1666596398169563138?s=20
- CMC URL: https://coinmarketcap.com/currencies/yolonolo/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-06-08 13:16 UTC, cinojosa0705 commented
I attest that the following information is correct:

[x] Mint Address: 4jE4VuqFWZfmSXjTDD5KUoN2qkVu96nPTPj4mhs5PA1W
[x] Symbol: YOLO
[x] Token Decimals: 6
[x] Token Icon: https://nftstorage.link/ipfs/bafkreia5uq5dr4nvgtb7dhrspmyov435vok7scobx4kbpwp7jwkuio5hxq
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

2023-06-08 17:17 UTC, tails3x commented
I attest that the following information is correct:

[x] Mint Address: 4jE4VuqFWZfmSXjTDD5KUoN2qkVu96nPTPj4mhs5PA1W
[x] Symbol: YOLO
[x] Token Decimals: 5
[x] Token Icon: https://nftstorage.link/ipfs/bafkreia5uq5dr4nvgtb7dhrspmyov435vok7scobx4kbpwp7jwkuio5hxq
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

2023-06-13 10:11 UTC, Timoon21 requested changes

2023-06-13 10:11 UTC, Timoon21 commented on validated-tokens.csv
> +YoloNolo Coin,YOLO,4jE4VuqFWZfmSXjTDD5KUoN2qkVu96nPTPj4mhs5PA1W,5,https://nftstorage.link/ipfs/bafkreia5uq5dr4nvgtb7dhrspmyov435vok7scobx4kbpwp7jwkuio5hxq,true
```suggestion
YoloNolo Coin,YOLO,4jE4VuqFWZfmSXjTDD5KUoN2qkVu96nPTPj4mhs5PA1W,5,https://nftstorage.link/ipfs/bafybeiepttutbes4mzojtmlvx3iqgwvs673czt5g7k7uoficx4vmjunmie/YOLO LOGO.png,true
```

2023-06-18 08:31 UTC, Timoon21 approved these changes
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

2023-06-20 04:39 UTC, merged