JEFF_Validation.csv
jup-ag/token-list pull request #247
Opened 2023-07-09 22:50 UTC by julesdamasta

# Validate [{JEFF}](https://solscan.io/token/FkCaFsprX7gySagFoQPHNbe9MRkjrvh21cokJo6C1e2T}) 

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/TheJeffcoinSOL
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [y] The metadata provided in the PR matches what is on-chain (Mandatory)
- [y] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [n] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [y ] My change matches the format in the file (no spaces between fields).
- [y ] My token is already live and trading on Jupiter.
- [y ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

2023-07-11 20:30 UTC, Timoon21 commented
Can you add a Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support ? Not just your twitter account.

I'll leave the PR open for now and review it again in a few days.

2023-07-12 18:10 UTC, julesdamasta commented
As requested... https://twitter.com/TheJeffcoinSOL/status/1679172618392330240?s=20

2023-07-14 15:33 UTC, Timoon21 requested changes

2023-07-14 15:33 UTC, Timoon21 commented on validated-tokens.csv
> +JEFF, JEFF,FkCaFsprX7gySagFoQPHNbe9MRkjrvh21cokJo6C1e2T,6,https://pbs.twimg.com/profile_images/1674243670747357185/mxqfTQkJ_400x400.jpg,true
```suggestion
JEFF, JEFF,FkCaFsprX7gySagFoQPHNbe9MRkjrvh21cokJo6C1e2T,6,https://arweave.net/Pi-s2vzZT8pfYVvFbNjgC0kSrW45PXb1_VPb5HoHuyI,true
```

2023-07-14 15:36 UTC, Timoon21 approved these changes
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation

2023-07-14 21:10 UTC, julesdamasta commented
ty!

2023-07-16 09:21 UTC, merged