Update validated-tokens.csv
jup-ag/token-list pull request #264
Opened 2023-07-26 08:24 UTC by iskeceli

SOUL token add

# Validate [{Token Symbol}](https://solscan.io/token/{mint_address})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [ ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ ] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [ ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

 Mint address: F6weWmuc1vwdL4u38Ro9jKXHEMjP9BoNdWMF5o5TvtJf
 Symbol: SOUL
 Token Decimals: 9
 Token icon: https://rkmp2iorabaal3oqws5jj233ruddww4itlhmkrigin5nctwm4isa.arweave.net/ipj9IdEAQAXt0LS6lOt7jQY7W4iazsVFBkN60U7M4iQ
 On-chain metadata matches

Community tweets: https://twitter.com/A2ZDAO/status/1684116507977195520

2023-07-27 09:59 UTC, iskeceli commented
Mint address: F6weWmuc1vwdL4u38Ro9jKXHEMjP9BoNdWMF5o5TvtJf
Symbol: SOUL
Token Decimals: 9
Token icon: https://rkmp2iorabaal3oqws5jj233ruddww4itlhmkrigin5nctwm4isa.arweave.net/ipj9IdEAQAXt0LS6lOt7jQY7W4iazsVFBkN60U7M4iQ
On-chain metadata matches

Community tweets: https://twitter.com/A2ZDAO/status/1684116507977195520

2023-07-29 16:04 UTC, Timoon21 requested changes

2023-07-29 16:04 UTC, Timoon21 commented on validated-tokens.csv
> +SOUL,SOUL,F6weWmuc1vwdL4u38Ro9jKXHEMjP9BoNdWMF5o5TvtJf,9,https://rkmp2iorabaal3oqws5jj233ruddww4itlhmkrigin5nctwm4isa.arweave.net/ipj9IdEAQAXt0LS6lOt7jQY7W4iazsVFBkN60U7M4iQ,true
```suggestion
SOUL,SOUL,F6weWmuc1vwdL4u38Ro9jKXHEMjP9BoNdWMF5o5TvtJf,9,https://arweave.net/ipj9IdEAQAXt0LS6lOt7jQY7W4iazsVFBkN60U7M4iQ,true
```

2023-07-29 16:06 UTC, Timoon21 submitted a review, later dismissed
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation

2023-07-29 20:04 UTC, iskeceli commented on validated-tokens.csv
> +SOUL,SOUL,F6weWmuc1vwdL4u38Ro9jKXHEMjP9BoNdWMF5o5TvtJf,9,https://rkmp2iorabaal3oqws5jj233ruddww4itlhmkrigin5nctwm4isa.arweave.net/ipj9IdEAQAXt0LS6lOt7jQY7W4iazsVFBkN60U7M4iQ,true
updated

2023-07-31 04:48 UTC, ArashiSol commented
@meijiao

2023-07-31 06:26 UTC, merged