Validate BATT
jup-ag/token-list pull request #30
Opened 2023-02-13 21:02 UTC by julesdamasta

# Validate [Token Symbol](https://solscan.io/token/BzjsQpgKjxZedFawUV9GZMExhr7VbvsasQv12v2PVxSt)

## Attestations:
- Tweet with Mint address: [https://twitter.com/{name}/status/{id}](https://twitter.com/bonk_bat)
- Coingecko/ CMC URL (If available): N/A

## Validation (Additonal material for reviewers):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
- [x] Is Listed on Coingecko / CMC (Optional, but might be helpful for reviewers to check for duplicates)  

## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

2023-02-13 21:26 UTC, Timoon21 requested changes
- [ ] Name and logoURI don't match metadata. **Please update PR.**
- [x] Token address matches the twitter account
- [x] No duplicare on CoinGecko
- [x] No duplicate on Jupiter's strict list
- [ ] Changes don't match the format **Please add _Community Validated_ field to _true_**

_According to on-chain metadata:
Name: 'Bat'
LogoURI: 'https://shdw-drive.genesysgo.net/8o6Mcb9id9oJJSjcsFtsWfs8NFHvQNqakz6CYjuShScB/bonkbat2.png'_

2023-02-13 21:34 UTC, julesdamasta commented
Good look, that is correct, Bat. I updated everything below as requested. Thanks for the quick responses. 

> On Feb 13, 2023, at 4:26 PM, Timoon21 ***@***.***> wrote:
> 
> 
> @Timoon21 requested changes on this pull request.
> 
>  Name and logoURI don't match metadata. Please update PR.
>  Token address matches the twitter account
>  No duplicare on CoinGecko
>  No duplicate on Jupiter's strict list
>  Changes don't match the format Please add Community Validated field to True
> According to on-chain metadata:
> Name: 'Bat'
> LogoURI: 'https://shdw-drive.genesysgo.net/8o6Mcb9id9oJJSjcsFtsWfs8NFHvQNqakz6CYjuShScB/bonkbat2.png'
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/jup-ag/token-list/pull/30#pullrequestreview-1296466225>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A534XD5UQ7F7N3S5JJHIIWLWXKRITANCNFSM6AAAAAAU2X7LNY>.
> You are receiving this because you authored the thread.
>

2023-02-14 00:14 UTC, LJQZZZ123 commented
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the twitter account
- [ ] No duplication on CoinGecko/ CMC
- [ ] Can be searched on CMC but untracked
- [ ] No duplication on Jupiter's strict list
> https://coinmarketcap.com/currencies/batt/

2023-02-14 00:22 UTC, LJQZZZ123 approved these changes

2023-02-14 06:01 UTC, merged