Validate I Choose Rich Everytime! (NICK)
jup-ag/token-list pull request #3068
Opened 2024-04-23 10:37 UTC by spwizard

# Validate [NICK](https://solscan.io/token/G3q2zUkuxDCXMnhdBPujjPHPw9UTMDbXqzcc2UHM3jiy)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/richnicksol/status/1782702199123922954

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

2024-04-23 18:32 UTC, Jymfletzfur approved these changes

2024-04-23 18:35 UTC, Jymfletzfur approved these changes

2024-04-25 14:52 UTC, 9yoi requested changes
I cannot load your image, please check. Use the one that's in your onchain metadata

2024-04-25 18:29 UTC, spwizard commented
> I cannot load your image, please check. Use the one that's in your onchain metadata

I have checked with the team and they want to use this one. I just retested it and it seems to display fine for me.

Is it a requirement that we have to use the one onChain as apparently that is the wrong image now.

<img width="736" alt="Screenshot 2024-04-25 at 19 28 16" src="https://github.com/jup-ag/token-list/assets/1477861/0c12d6db-793a-4adb-8a2c-c1cb0661a1ea">

2024-04-28 16:04 UTC, 9yoi commented
I am unable to load your image and it does not match the onchain metadata image, which is https://bafkreigzternd6pcuni3d56amd5vrilsfp66jtg3nfdpafli6byz4nljhi.ipfs.nftstorage.link/
![Screenshot 2024-04-29 at 12 03 47 AM](https://github.com/jup-ag/token-list/assets/15177990/a5aa9b20-9352-498b-998d-44a3ef0d92c9)

2024-04-29 12:23 UTC, closed without merging