add blackfin AI to strict list
jup-ag/token-list pull request #3090
Opened 2024-04-24 03:55 UTC by 0xSoju2

2024-04-24 04:00 UTC, wkitsin requested changes

2024-04-24 04:00 UTC, wkitsin commented on validated-tokens.csv
> +Blackfin AI,BLKFN,BLKFNuCET9ZnmhFczGXmcWKSap9kGtTFnosvA9P5majk,9https://ipfs.io/ipfs/QmP5jmqEB1zZ8KZyAwRuQg9NGDPH4kcgB42Ao3YK66QPTZ,true
you missed a comma, behind `9`

2024-04-25 00:21 UTC, Aymanabc reviewed
Good to go

2024-04-25 00:21 UTC, Aymanabc commented on validated-tokens.csv
Good to go

2024-04-25 02:09 UTC, wkitsin approved these changes

2024-04-25 06:54 UTC, ZhengYuTay approved these changes

2024-04-25 13:36 UTC, zaikshev88 approved these changes

2024-04-25 13:39 UTC, merged