Validate ju
jup-ag/token-list pull request #3193
Opened 2024-04-27 21:00 UTC by agentPretzel

# Validate [ju](https://solscan.io/token/AbBEjBdz31yCb9gTFfWgEi7uprCzjTEKL58xqHVbbjhu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/jurugancoin/status/1784324630708093157
- Coingecko/ CMC URL (If available): Coingecko and CMC are work in progress. Auto-generated CMC link of ju:
https://coinmarketcap.com/dexscan/solana/F89N3zMU17HtYaFfL4APQwM3MRjFwnkjc6tN7oXxRD9J/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

2024-05-04 21:30 UTC, Jymfletzfur approved these changes

2024-05-05 10:27 UTC, 9yoi requested changes
The icon link does not load for me

2024-05-05 18:55 UTC, agentPretzel commented
> The icon link does not load for me

I grabbed the image from the token metadata. The image link auto-downloads for me (does not load in browser tho)
The $ju token is a community takeover now, the dev rugged/jeeted his bags and the community is running it (i am part of the community).

Sadly, the token metadata in this case cannot be modified so unfortunately this is the image, alternatively, we can host the same image somewhere else and I can change the link?

Please let me know if that's sufficient. $ju already got some partnerships and their mcap has increased significantly - we definitely do not want anybody copying us and scamming less knowledgable Jupiter users.

2024-05-06 09:08 UTC, 9yoi approved these changes

2024-05-06 09:08 UTC, merged