Validate DUAL
jup-ag/token-list pull request #82
Opened 2023-03-02 16:01 UTC by DonDuala

# Validate [DUAL](https://solscan.io/token/DUALa4FC2yREwZ59PHeu1un4wis36vHRv5hWVBmzykCJ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: Will add later today as part of the launch announcement from https://twitter.com/DualFinance 
- Coingecko/ CMC URL (If available): Submitted request on 3/2/2023. Currently pending but should be at https://www.coingecko.com/en/coins/dual in 3-5 days

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  Submitted, not listed yet

## Acknowledgement (Please check off boxes)
- [x] I did not modify unrelated code.
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and will get community support on Twitter.

2023-03-03 01:12 UTC, Timoon21 requested changes
Deleting spaces to match the format in the file (no spaces between fields).

2023-03-03 01:12 UTC, Timoon21 commented on validated-tokens.csv
> +Dual DAO Token, DUAL, DUALa4FC2yREwZ59PHeu1un4wis36vHRv5hWVBmzykCJ, 6, https://www.dual.finance/images/token-logos/dual.png, true
```suggestion
Dual DAO Token,DUAL,DUALa4FC2yREwZ59PHeu1un4wis36vHRv5hWVBmzykCJ,6,https://www.dual.finance/images/token-logos/dual.png,true
```

2023-03-04 03:49 UTC, DonDuala commented
Tweet: https://twitter.com/DualFinance/status/1631864211050582017?s=20
Coingecko here: https://www.coingecko.com/en/coins/dual-finance

2023-03-05 01:02 UTC, Timoon21 submitted a review, later dismissed

2023-03-05 13:21 UTC, merged